In [1]:
%load_ext autoreload
%autoreload 2

import sys
import os

import pandas as pd

script_folder = os.path.abspath(os.path.join('..', 'src'))

if script_folder not in sys.path:
    sys.path.append(script_folder)

import download_data as downloader

import data_processing as pr

In [47]:
#download data

In [2]:
df_weather_meta = downloader.download_chmi_weather_stations_metadata()

df_weather_meta.head()

,WSI,GH_ID,BEGIN_DATE,END_DATE,FULL_NAME,GEOGR1,GEOGR2,ELEVATION
0,0-20000-0-04030,ZIS04030,2015-01-01T00:00:00Z,3999-12-31T23:59:00Z,Reykjavik,-21.903905,64.127653,51.0
1,0-20000-0-11406,L3CHEB01,1863-10-01T00:00:00Z,1919-12-31T23:59:00Z,Cheb,12.362892,50.076212,458.0
2,0-20000-0-11406,L3CHEB01,1933-05-07T00:00:00Z,1938-04-30T23:59:00Z,Cheb,12.388900,50.0739,471.0
3,0-20000-0-11406,L3CHEB01,1943-06-01T00:00:00Z,1945-01-31T23:59:00Z,Cheb,12.388900,50.0739,471.0
4,0-20000-0-11406,L3CHEB01,1951-01-01T00:00:00Z,1960-12-31T23:59:00Z,Cheb,12.388900,50.0739,471.0

In [3]:
df_weather_stats_meta = downloader.download_chmi_weather_variables_metadata()

df_weather_stats_meta.head()

,OBS_TYPE,WSI,BEGIN_DATE,END_DATE,EG_EL_ABBREVIATION,NAME,UN_DESCRIPTION,HEIGHT,SCHEDULE
0,DLY,0-20000-0-11406,1863-10-01T00:00:00Z,1919-12-31T23:59:00Z,T,Teplota,°C,2.0,"AVG,06:00,13:00,20:00"
1,DLY,0-20000-0-11406,1865-06-01T00:00:00Z,1919-12-31T23:59:00Z,TMI,Teplota min,°C,2.0,20:00
2,DLY,0-20000-0-11406,1865-06-01T00:00:00Z,1919-12-31T23:59:00Z,TMA,Teplota max,°C,2.0,20:00
3,DLY,0-20000-0-11406,1933-05-07T00:00:00Z,1938-04-30T23:59:00Z,SSV,Sluneční svit,hod,2.0,00:00
4,DLY,0-20000-0-11406,1943-06-01T00:00:00Z,1945-01-31T23:59:00Z,SSV,Sluneční svit,hod,2.0,00:00

In [4]:
wsi_dict = downloader.build_and_save_wsi_dict()

print(f"Found {len(wsi_dict)} Prague weather stations:")
print(pd.DataFrame(list(wsi_dict.items()), columns=["key", "value"]))

Found 9 Prague weather stations:
                   key               value
0  0-203-0-10904013001     Praha, Komořany
1      0-20000-0-11567        Praha, Kbely
2  0-203-0-11201024001      Praha, Břevnov
3      0-20000-0-11520        Praha, Libuš
4      0-20000-0-11519       Praha, Karlov
5        0-203-0-11514  Praha, Klementinum
6      0-20000-0-11518       Praha, Ruzyně
7        0-203-0-11515  Praha, Klementinum
8  0-203-0-11101007001         Praha, Brdy

In [5]:
df_weather = downloader.download_chmi_weather_data()

display(df_weather.info())
display(df_weather.head())

Loaded 0-203-0-10904013001 Praha, Komořany
Loaded 0-20000-0-11567 Praha, Kbely
Loaded 0-203-0-11201024001 Praha, Břevnov
Request failed for 0-20000-0-11520 Praha, Libuš 2025-11: HTTPSConnectionPool(host='opendata.chmi.cz', port=443): Max retries exceeded with url: /meteorology/climate/historical/data/10min/2025/10m-0-20000-0-11520-202511.json (Caused by ConnectTimeoutError(<HTTPSConnection(host='opendata.chmi.cz', port=443) at 0x2b5a2273890>, 'Connection to opendata.chmi.cz timed out. (connect timeout=90)'))
Loaded 0-20000-0-11520 Praha, Libuš
Loaded 0-20000-0-11519 Praha, Karlov
Loaded 0-203-0-11514 Praha, Klementinum
Loaded 0-20000-0-11518 Praha, Ruzyně
Loaded 0-203-0-11515 Praha, Klementinum
Loaded 0-203-0-11101007001 Praha, Brdy
<class 'pandas.DataFrame'>
RangeIndex: 4954686 entries, 0 to 4954685
Data columns (total 9 columns):
 #   Column   Dtype
---  ------   -----
 0   STATION  str
 1   ELEMENT  str
 2   DT       str
 3   VAL      object
 4   FLAG     str
 5   QUALITY  float64
 6   WSI      str
 7   YEAR     str
 8   MONTH    str
dtypes: float64(1), object(1), str(7)
memory usage: 623.3+ MB

None

,STATION,ELEMENT,DT,VAL,FLAG,QUALITY,WSI,YEAR,MONTH
0,0-203-0-10904013001,H,2025-01-01T00:00:00Z,93.0,,0.0,0-203-0-10904013001,2025,01
1,0-203-0-10904013001,H,2025-01-01T00:10:00Z,93.0,,0.0,0-203-0-10904013001,2025,01
2,0-203-0-10904013001,H,2025-01-01T00:20:00Z,93.0,,0.0,0-203-0-10904013001,2025,01
3,0-203-0-10904013001,H,2025-01-01T00:30:00Z,93.0,,0.0,0-203-0-10904013001,2025,01
4,0-203-0-10904013001,H,2025-01-01T00:40:00Z,93.0,,0.0,0-203-0-10904013001,2025,01

In [6]:
air_qual_meta = downloader.download_airquality_metadata()

air_qual_meta.head()

,id_registration,station_code,locality_code,locality_name,street,city,lon,lat,alt,component_code,component_name,unit
39,783575,AREPA,AREP,Praha 1-n. Republiky,,,14.429220,50.088066,190 m,NO2,oxid dusičitý,ug/m^3
40,783579,AREPA,AREP,Praha 1-n. Republiky,,,14.429220,50.088066,190 m,NOx,oxidy dusíku,ug/m^3
41,783591,AREPA,AREP,Praha 1-n. Republiky,,,14.429220,50.088066,190 m,PM10,částice PM10,ug/m^3
42,1648334,AREPA,AREP,Praha 1-n. Republiky,,,14.429220,50.088066,190 m,INDX,Index kvality ovzduší,
66,41157,ALEGA,ALEG,Praha 2-Legerova (hot spot),Legerov 1843,Praha 2,14.430673,50.072388,219 m,NO2,oxid dusičitý,ug/m^3

In [7]:
air_stat_dict = downloader.build_and_save_air_stations_dict()

print(f"Found {len(air_stat_dict)} Prague air stations:")
print(pd.DataFrame(list(air_stat_dict.items()), columns=["key", "value"]))

Found 14 Prague air stations:
      key                        value
0   AREPA         Praha 1-n. Republiky
1   ALEGA  Praha 2-Legerova (hot spot)
2   AKALA               Praha 8-Karlín
3   AVYNA             Praha 9-Vysočany
4   ALIBA                Praha 4-Libuš
5   ASTOA             Praha 5-Stodůlky
6   APRUA          Praha 10-Průmyslová
7   AHOLA           Praha 7-Holešovice
8   AKOBA             Praha 8-Kobylisy
9   ASUCA              Praha 6-Suchdol
10  ARIEA        Praha 2-Riegrovy sady
11  AVRSA            Praha 10-Vršovice
12  ABREA              Praha 6-Břevnov
13  ACHOA               Praha 4-Chodov

In [8]:
#####  runs for 40 minutes

# air_quality_data = downloader.download_airquality_data()

# air_quality_data.head()

In [9]:
# data processing

In [10]:
repo_root, data_raw_path, data_processed_path = pr.get_paths()
repo_root, data_raw_path, data_processed_path

(WindowsPath('C:/Users/jachy/Desktop/Data-Processing-in-Python---Project'),
 WindowsPath('C:/Users/jachy/Desktop/Data-Processing-in-Python---Project/data/raw'),
 WindowsPath('C:/Users/jachy/Desktop/Data-Processing-in-Python---Project/data/processed'))

In [11]:
# process station metadata
weather_stations_meta = pr.process_weather_stations(data_raw_path)

weather_stations_meta.head()

,WSI,GH_ID,BEGIN_DATE,END_DATE,FULL_NAME,GEOGR1,GEOGR2,ELEVATION,BEGIN_DATE_DT,END_DATE_DT
1101,0-203-0-10904013001,P1PKOM01,2017-12-07T12:00:00Z,3999-12-31T23:59:00Z,"Praha, Komořany",14.406360,49.988600,213.00,2017-12-07 12:00:00+00:00,3999-12-31 23:59:00+00:00
2214,0-203-0-11514,P1PKLE01,2023-01-01T00:00:00Z,3999-12-31T23:59:00Z,"Praha, Klementinum",14.416923,50.086634,190.70,2023-01-01 00:00:00+00:00,3999-12-31 23:59:00+00:00
75,0-20000-0-11567,P1PKBE01,2010-10-01T00:00:00Z,3999-12-31T23:59:00Z,"Praha, Kbely",14.538056,50.123333,284.50,2010-10-01 00:00:00+00:00,3999-12-31 23:59:00+00:00
68,0-20000-0-11520,P1PLIB01,2018-05-17T00:00:00Z,3999-12-31T23:59:00Z,"Praha, Libuš",14.446944,50.007778,302.04,2018-05-17 00:00:00+00:00,3999-12-31 23:59:00+00:00
1429,0-203-0-11201024001,P1PBRE01,2013-09-01T00:00:00Z,3999-12-31T23:59:00Z,"Praha, Břevnov",14.352689,50.080843,355.00,2013-09-01 00:00:00+00:00,3999-12-31 23:59:00+00:00

In [12]:
df_weather_hourly = pr.aggregate_weather_10min_to_hourly(data_raw_path)

df_weather_hourly.head()

c:\Users\jachy\Desktop\Data-Processing-in-Python---Project\src\data_processing.py:82: DtypeWarning: Columns (0: FLAG) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_raw_path / "weather_data_10min.csv")

,STATION,WSI,ELEMENT,DT,VAL,YEAR,MONTH,ELEMENT_NAME,WSI_NAME
0,0-20000-0-11518,0-20000-0-11518,Casmax,2025-01-01 00:00:00+00:00,98.500000,2025,1,Čas maxima,"Praha, Ruzyně"
1,0-20000-0-11518,0-20000-0-11518,D,2025-01-01 00:00:00+00:00,199.287437,2025,1,Směr větru,"Praha, Ruzyně"
2,0-20000-0-11518,0-20000-0-11518,Dmax,2025-01-01 00:00:00+00:00,206.166667,2025,1,Směr Fmax,"Praha, Ruzyně"
3,0-20000-0-11518,0-20000-0-11518,Dprum,2025-01-01 00:00:00+00:00,200.254152,2025,1,Směr větru prům,"Praha, Ruzyně"
4,0-20000-0-11518,0-20000-0-11518,F,2025-01-01 00:00:00+00:00,2.633333,2025,1,Rychlost větru,"Praha, Ruzyně"

In [13]:
df_weather_ext = pr.load_and_merge_weather_station_metadata(df_weather_hourly, weather_stations_meta)

df_weather_ext.head()

,STATION,WSI,ELEMENT,DT,VAL,YEAR,MONTH,ELEMENT_NAME,WSI_NAME,FULL_NAME,ELEVATION,LON,LAT
0,0-20000-0-11518,0-20000-0-11518,Casmax,2025-01-01 00:00:00+00:00,98.500000,2025,1,Čas maxima,"Praha, Ruzyně","Praha, Ruzyně",364.0,14.255556,50.100278
1,0-20000-0-11518,0-20000-0-11518,D,2025-01-01 00:00:00+00:00,199.287437,2025,1,Směr větru,"Praha, Ruzyně","Praha, Ruzyně",364.0,14.255556,50.100278
2,0-20000-0-11518,0-20000-0-11518,Dmax,2025-01-01 00:00:00+00:00,206.166667,2025,1,Směr Fmax,"Praha, Ruzyně","Praha, Ruzyně",364.0,14.255556,50.100278
3,0-20000-0-11518,0-20000-0-11518,Dprum,2025-01-01 00:00:00+00:00,200.254152,2025,1,Směr větru prům,"Praha, Ruzyně","Praha, Ruzyně",364.0,14.255556,50.100278
4,0-20000-0-11518,0-20000-0-11518,F,2025-01-01 00:00:00+00:00,2.633333,2025,1,Rychlost větru,"Praha, Ruzyně","Praha, Ruzyně",364.0,14.255556,50.100278

In [14]:
air_stations_meta = pr.load_air_quality_meta(data_raw_path)

air_stations_meta.head()

,id_registration,station_code,locality_code,locality_name,street,city,lon,lat,alt,component_code,component_name,unit
0,783575,AREPA,AREP,Praha 1-n. Republiky,NaN,NaN,14.429220,50.088066,190 m,NO2,oxid dusičitý,ug/m^3
1,783579,AREPA,AREP,Praha 1-n. Republiky,NaN,NaN,14.429220,50.088066,190 m,NOx,oxidy dusíku,ug/m^3
2,783591,AREPA,AREP,Praha 1-n. Republiky,NaN,NaN,14.429220,50.088066,190 m,PM10,částice PM10,ug/m^3
3,1648334,AREPA,AREP,Praha 1-n. Republiky,NaN,NaN,14.429220,50.088066,190 m,INDX,Index kvality ovzduší,NaN
4,41157,ALEGA,ALEG,Praha 2-Legerova (hot spot),Legerov 1843,Praha 2,14.430673,50.072388,219 m,NO2,oxid dusičitý,ug/m^3

In [ ]:
df_air_qual = pr.load_and_merge_air_quality_data(air_stations_meta, data_raw_path)

df_air_qual.head()

In [ ]:
nearest_match = pr.spatial_join_stations(air_stations_meta, weather_stations_meta)

nearest_match.head()

,air_station_code,air_station_name,air_lon,air_lat,air_alt,weather_station_id,weather_station_name,weather_lon,weather_lat,weather_alt,distance_m,distance_km
0,AREPA,Praha 1-n. Republiky,14.429220,50.088066,190 m,0-203-0-11514,"Praha, Klementinum",14.416923,50.086634,190.70,894.275861,0.894276
4,ALEGA,Praha 2-Legerova (hot spot),14.430673,50.072388,219 m,0-20000-0-11519,"Praha, Karlov",14.427778,50.069167,260.50,413.820395,0.413820
10,AKALA,Praha 8-Karlín,14.442049,50.094238,203 m,0-203-0-11514,"Praha, Klementinum",14.416923,50.086634,190.70,1986.875839,1.986876
14,AVYNA,Praha 9-Vysočany,14.503096,50.111080,219 m,0-20000-0-11567,"Praha, Kbely",14.538056,50.123333,284.50,2847.472186,2.847472
19,ALIBA,Praha 4-Libuš,14.445933,50.007305,301 m,0-20000-0-11520,"Praha, Libuš",14.446944,50.007778,302.04,89.518322,0.089518

In [ ]:
df_merged = pr.process_and_merge_air_weather_data(df_air_qual, df_weather_ext, nearest_match)

df_merged.head()

,startTime,weather_station_name,air_station_name,air_NO2,air_NOx,air_PM10,weather_D,weather_Dmax,weather_Dprum,weather_F,...,weather_SRA10M,weather_T,weather_TMA,weather_TMI,air_lon,air_lat,weather_lon,weather_lat,weather_alt,distance_km
0,2025-01-01,"Praha, Klementinum",Praha 1-n. Republiky,28.3,118.6,240.9,311.460580,197.000000,239.188728,0.550000,...,0.0,-2.216667,-1.7,-2.2,14.429220,50.088066,14.416923,50.086634,190.70,0.894276
2,2025-01-01,"Praha, Karlov",Praha 10-Vršovice,22.6,72.5,162.5,96.321908,102.333333,96.486216,2.000000,...,0.0,-4.600000,-4.2,-4.9,14.446152,50.066429,14.427778,50.069167,260.50,1.350129
3,2025-01-01,"Praha, Karlov",Praha 2-Legerova (hot spot),33.3,179.0,233.5,96.321908,102.333333,96.486216,2.000000,...,0.0,-4.600000,-4.2,-4.9,14.430673,50.072388,14.427778,50.069167,260.50,0.413820
4,2025-01-01,"Praha, Karlov",Praha 2-Riegrovy sady,25.4,90.9,174.0,96.321908,102.333333,96.486216,2.000000,...,0.0,-4.600000,-4.2,-4.9,14.442692,50.081482,14.427778,50.069167,260.50,1.736525
6,2025-01-01,"Praha, Libuš",Praha 4-Libuš,24.5,47.1,76.8,244.851781,217.000000,242.042425,1.283333,...,0.0,-4.033333,-3.2,-4.3,14.445933,50.007305,14.446944,50.007778,302.04,0.089518

In [ ]:
df_merged.columns

Index(['startTime', 'weather_station_name', 'air_station_name', 'air_NO2',
       'air_NOx', 'air_PM10', 'weather_D', 'weather_Dmax', 'weather_Dprum',
       'weather_F', 'weather_Fmax', 'weather_Fprum', 'weather_H', 'weather_P',
       'weather_SRA10M', 'weather_T', 'weather_TMA', 'weather_TMI', 'air_lon',
       'air_lat', 'weather_lon', 'weather_lat', 'weather_alt', 'distance_km'],
      dtype='str')

In [ ]:
df_cleaned = pr.clean_data(df_merged)

df_cleaned.head()

,startTime,weather_station_name,air_station_name,air_NO2,air_NOx,air_PM10,weather_D,weather_Dmax,weather_Dprum,weather_F,...,weather_SRA10M,weather_T,weather_TMA,weather_TMI,air_lon,air_lat,weather_lon,weather_lat,weather_alt,distance_km
0,2025-01-01,"Praha, Klementinum",Praha 1-n. Republiky,28.3,118.6,240.9,311.460580,197.000000,239.188728,0.550000,...,0.0,-2.216667,-1.7,-2.2,14.429220,50.088066,14.416923,50.086634,190.70,0.894276
2,2025-01-01,"Praha, Karlov",Praha 10-Vršovice,22.6,72.5,162.5,96.321908,102.333333,96.486216,2.000000,...,0.0,-4.600000,-4.2,-4.9,14.446152,50.066429,14.427778,50.069167,260.50,1.350129
3,2025-01-01,"Praha, Karlov",Praha 2-Legerova (hot spot),33.3,179.0,233.5,96.321908,102.333333,96.486216,2.000000,...,0.0,-4.600000,-4.2,-4.9,14.430673,50.072388,14.427778,50.069167,260.50,0.413820
4,2025-01-01,"Praha, Karlov",Praha 2-Riegrovy sady,25.4,90.9,174.0,96.321908,102.333333,96.486216,2.000000,...,0.0,-4.600000,-4.2,-4.9,14.442692,50.081482,14.427778,50.069167,260.50,1.736525
6,2025-01-01,"Praha, Libuš",Praha 4-Libuš,24.5,47.1,76.8,244.851781,217.000000,242.042425,1.283333,...,0.0,-4.033333,-3.2,-4.3,14.445933,50.007305,14.446944,50.007778,302.04,0.089518

In [ ]:
df_final = pr.engineer_features(df_cleaned)

df_final.head()

,startTime,weather_station_name,air_station_name,air_NO2,air_NOx,air_PM10,weather_D,weather_Dmax,weather_Dprum,weather_F,...,weather_H_mean3,weather_H_mean6,weather_P_lag1,weather_P_mean3,weather_P_mean6,precip_sum3,precip_sum6,precip_sum12,precip_sum24,weather_P_change6
0,2025-01-01 00:00:00,"Praha, Klementinum",Praha 1-n. Republiky,28.3,118.6,240.9,311.460580,197.000000,239.188728,0.550000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-01-01 01:00:00,"Praha, Klementinum",Praha 1-n. Republiky,23.9,97.0,230.2,4.811233,162.166667,20.826144,0.716667,...,85.333333,85.333333,1001.616667,1001.616667,1001.616667,0.0,0.0,0.0,0.0,NaN
2,2025-01-01 02:00:00,"Praha, Klementinum",Praha 1-n. Republiky,24.7,107.7,177.9,326.036679,241.833333,271.388062,0.400000,...,83.916667,83.916667,1001.466667,1001.541667,1001.541667,0.0,0.0,0.0,0.0,NaN
3,2025-01-01 03:00:00,"Praha, Klementinum",Praha 1-n. Republiky,30.0,146.0,157.0,224.797622,212.000000,216.537033,1.416667,...,83.333333,83.333333,1001.183333,1001.422222,1001.422222,0.0,0.0,0.0,0.0,NaN
4,2025-01-01 04:00:00,"Praha, Klementinum",Praha 1-n. Republiky,28.7,159.7,128.2,243.837434,213.000000,219.474988,0.850000,...,82.444444,83.166667,1001.100000,1001.250000,1001.341667,0.0,0.0,0.0,0.0,NaN

In [ ]:
df_final.shape

(69776, 56)

In [ ]:
print([df_final.startTime.min(),
df_final.startTime.max()])

print(df_final.weather_station_name.unique())
print(df_final.air_station_name.unique())

[Timestamp('2025-01-01 00:00:00'), Timestamp('2025-12-31 23:00:00')]
<ArrowStringArray>
['Praha, Klementinum', 'Praha, Karlov', 'Praha, Libuš', 'Praha, Kbely']
Length: 4, dtype: str
<ArrowStringArray>
[       'Praha 1-n. Republiky',           'Praha 10-Vršovice',
 'Praha 2-Legerova (hot spot)',       'Praha 2-Riegrovy sady',
               'Praha 4-Libuš',          'Praha 7-Holešovice',
              'Praha 8-Karlín',            'Praha 9-Vysočany']
Length: 8, dtype: str

In [ ]:
df_final.isna().sum().sort_values(ascending=False)

air_NOx                 4155
air_NO2                 4062
air_PM10                1095
weather_P_change6         48
weather_P_mean3            8
weather_P_mean6            8
weather_P_lag1             8
precip_sum12               8
weather_H_mean6            8
wind_v_mean3               8
weather_T_lag1             8
wind_v_mean6               8
weather_T_mean6            8
weather_H_lag1             8
weather_H_mean3            8
weather_T_mean3            8
wind_u_mean6               8
weather_F_lag1             8
weather_F_mean6            8
weather_F_mean3            8
wind_v_lag1                8
wind_u_mean3               8
wind_u_lag1                8
precip_sum3                8
precip_sum24               8
precip_sum6                8
distance_km                0
weather_lon                0
air_lat                    0
weather_alt                0
weather_lat                0
weather_TMA                0
weather_T                  0
weather_SRA10M             0
weather_P                  0
weather_H                  0
weather_Fprum              0
weather_Fmax               0
weather_F                  0
weather_Dprum              0
weather_Dmax               0
weather_D                  0
weather_station_name       0
air_station_name           0
startTime                  0
air_lon                    0
weather_TMI                0
wind_v                     0
hour                       0
dayofweek                  0
is_weekend                 0
date                       0
month                      0
dayofyear                  0
weekday_name               0
wind_u                     0
dtype: int64

In [ ]:
out_path = pr.save_processed(df_final, data_processed_path)
print(f"Saved processed data to: {out_path}")

Saved processed data to: C:\Users\jachy\Desktop\Data-Processing-in-Python---Project\data\processed\processed_data.csv