In [ ]:
### data download

In [34]:
import os
proj_root = os.path.abspath(os.path.join(os.getcwd(), ".."))   # notebooks/ -> project root
data_dir = os.path.join(proj_root, "data", "raw")
os.makedirs(data_dir, exist_ok=True)

In [35]:
import os, sys
print(data_dir)
print("cwd:", os.getcwd())
print("src exists:", os.path.exists(os.path.join(os.getcwd(), "src")))
print("sys.path[0]:", sys.path[0])

c:\Users\jachy\Desktop\Data-Processing-in-Python---Project\data\raw
cwd: c:\Users\jachy\Desktop\Data-Processing-in-Python---Project\notebooks
src exists: False
sys.path[0]: c:\Users\jachy\Desktop\Data-Processing-in-Python---Project

In [36]:
### import funcctions from .py to download the data
from src.download_data import (
    download_metadata,
    download_latest_data,
    get_chmi_weather_stations_metadata,
    get_chmi_weather_variables_metadata,
    get_chmi_weather_data,
    get_airquality_stations_metadata,
)

In [37]:
# chmi metadata

get_chmi_weather_stations_metadata(out_path=os.path.join(data_dir, "chmi_stations_metadata.csv"))
get_chmi_weather_variables_metadata(out_path=os.path.join(data_dir, "chmi_variables_metadata.csv"))

,OBS_TYPE,WSI,BEGIN_DATE,END_DATE,EG_EL_ABBREVIATION,NAME,UN_DESCRIPTION,HEIGHT,SCHEDULE
0,DLY,0-20000-0-11406,1865-06-01T00:00:00Z,1919-12-31T23:59:00Z,TMA,Teplota max,°C,2.0,20:00
1,DLY,0-20000-0-11406,1865-06-01T00:00:00Z,1919-12-31T23:59:00Z,TMI,Teplota min,°C,2.0,20:00
2,DLY,0-20000-0-11406,1863-10-01T00:00:00Z,1919-12-31T23:59:00Z,T,Teplota,°C,2.0,"06:00,13:00,20:00,AVG"
3,DLY,0-20000-0-11406,1933-05-07T00:00:00Z,1938-04-30T23:59:00Z,SSV,Sluneční svit,hod,2.0,00:00
4,DLY,0-20000-0-11406,1943-06-01T00:00:00Z,1945-01-31T23:59:00Z,SSV,Sluneční svit,hod,2.0,00:00
...,...,...,...,...,...,...,...,...,...
80483,10M,0-203-0-42108066001,2018-02-09T00:00:00Z,3999-12-31T23:59:00Z,SRA10M,Srážka-10M,mm,1.0,10M
80484,10M,0-203-0-42109005003,2015-09-16T00:00:00Z,3999-12-31T23:59:00Z,H,Vlhkost relat,%,2.0,10M
80485,10M,0-203-0-42109005003,2015-09-16T00:00:00Z,3999-12-31T23:59:00Z,SVHa,Vodní hodnota,mm,0.0,10M
80486,10M,0-203-0-42109005003,2015-09-16T00:00:00Z,3999-12-31T23:59:00Z,SCEa,Výška sněhu,cm,0.0,10M
80487,10M,0-203-0-42109005003,2015-09-16T00:00:00Z,3999-12-31T23:59:00Z,T,Teplota,°C,2.0,10M

In [38]:
# CHMI data

get_chmi_weather_data(
    start_year=2025, 
    end_year=2025, 
    wsi_csv=os.path.join(data_dir, "wsi_dict.csv"),  
    out_path=os.path.join(data_dir, "weather_data_10min.csv")
)

Request failed for 0-203-0-11201020003 Praha, Chodov 2025 01: 404 Client Error: Not Found for url: https://opendata.chmi.cz//meteorology/climate/historical/data/10min/2025/10m-0-203-0-11201020003-202501.json
Request failed for 0-203-0-11201020003 Praha, Chodov 2025 02: 404 Client Error: Not Found for url: https://opendata.chmi.cz//meteorology/climate/historical/data/10min/2025/10m-0-203-0-11201020003-202502.json
Request failed for 0-203-0-11201020003 Praha, Chodov 2025 03: 404 Client Error: Not Found for url: https://opendata.chmi.cz//meteorology/climate/historical/data/10min/2025/10m-0-203-0-11201020003-202503.json
Request failed for 0-203-0-11201020003 Praha, Chodov 2025 04: 404 Client Error: Not Found for url: https://opendata.chmi.cz//meteorology/climate/historical/data/10min/2025/10m-0-203-0-11201020003-202504.json
Request failed for 0-203-0-11201020003 Praha, Chodov 2025 05: 404 Client Error: Not Found for url: https://opendata.chmi.cz//meteorology/climate/historical/data/10min/2025/10m-0-203-0-11201020003-202505.json
Request failed for 0-203-0-11201020003 Praha, Chodov 2025 06: 404 Client Error: Not Found for url: https://opendata.chmi.cz//meteorology/climate/historical/data/10min/2025/10m-0-203-0-11201020003-202506.json
Request failed for 0-203-0-11201020003 Praha, Chodov 2025 07: 404 Client Error: Not Found for url: https://opendata.chmi.cz//meteorology/climate/historical/data/10min/2025/10m-0-203-0-11201020003-202507.json
Request failed for 0-203-0-11201020003 Praha, Chodov 2025 08: 404 Client Error: Not Found for url: https://opendata.chmi.cz//meteorology/climate/historical/data/10min/2025/10m-0-203-0-11201020003-202508.json
Request failed for 0-203-0-11201020003 Praha, Chodov 2025 09: 404 Client Error: Not Found for url: https://opendata.chmi.cz//meteorology/climate/historical/data/10min/2025/10m-0-203-0-11201020003-202509.json
Request failed for 0-203-0-11201020003 Praha, Chodov 2025 10: 404 Client Error: Not Found for url: https://opendata.chmi.cz//meteorology/climate/historical/data/10min/2025/10m-0-203-0-11201020003-202510.json
Request failed for 0-203-0-11201020003 Praha, Chodov 2025 11: 404 Client Error: Not Found for url: https://opendata.chmi.cz//meteorology/climate/historical/data/10min/2025/10m-0-203-0-11201020003-202511.json
Request failed for 0-203-0-11201020003 Praha, Chodov 2025 12: 404 Client Error: Not Found for url: https://opendata.chmi.cz//meteorology/climate/historical/data/10min/2025/10m-0-203-0-11201020003-202512.json

,STATION,ELEMENT,DT,VAL,FLAG,QUALITY,WSI,YEAR,MONTH
0,0-20000-0-11518,Casmax,2025-01-01T00:00:00Z,273.0,,0.0,0-20000-0-11518,2025,01
1,0-20000-0-11518,Casmax,2025-01-01T00:10:00Z,32.0,,0.0,0-20000-0-11518,2025,01
2,0-20000-0-11518,Casmax,2025-01-01T00:20:00Z,1.0,,0.0,0-20000-0-11518,2025,01
3,0-20000-0-11518,Casmax,2025-01-01T00:30:00Z,283.0,,0.0,0-20000-0-11518,2025,01
4,0-20000-0-11518,Casmax,2025-01-01T00:40:00Z,1.0,,0.0,0-20000-0-11518,2025,01
...,...,...,...,...,...,...,...,...,...
5045395,0-203-0-11101007001,T,2025-12-31T23:10:00Z,-3.7,,0.0,0-203-0-11101007001,2025,12
5045396,0-203-0-11101007001,T,2025-12-31T23:20:00Z,-3.6,,0.0,0-203-0-11101007001,2025,12
5045397,0-203-0-11101007001,T,2025-12-31T23:30:00Z,-3.6,,0.0,0-203-0-11101007001,2025,12
5045398,0-203-0-11101007001,T,2025-12-31T23:40:00Z,-3.6,,0.0,0-203-0-11101007001,2025,12
5045399,0-203-0-11101007001,T,2025-12-31T23:50:00Z,-3.5,,0.0,0-203-0-11101007001,2025,12

In [39]:
# CHMI air-quality files
META_URL = "https://opendata.chmi.cz/air_quality/recent/metadata/metadata.json"
DATA_URL = "https://opendata.chmi.cz/air_quality/recent/data/"
download_metadata(META_URL, out_path=os.path.join(data_dir, "airquality_CHMI_stations_metadata.csv"))
download_latest_data(DATA_URL, out_path=os.path.join(data_dir,"airquality_CHMI_stations_data.csv"))

Downloading raw data from: airquality_1h_avg_CZ_2026050111.csv

     idRegistration              startTime   idValueType   value
0             10221   2026-05-01T11:00:00Z             8     4.0
1             40237   2026-05-01T11:00:00Z             8     6.3
2             40238   2026-05-01T11:00:00Z             8   108.1
3             40244   2026-05-01T11:00:00Z             8   102.7
4             40257   2026-05-01T11:00:00Z             8     1.3
..              ...                    ...           ...     ...
467         2181672   2026-05-01T11:00:00Z             8    10.4
468         2181676   2026-05-01T11:00:00Z             8     5.0
469         2187304   2026-05-01T11:00:00Z             8    12.7
470         2187315   2026-05-01T11:00:00Z             8     4.5
471         2200581   2026-05-01T11:00:00Z             8     1.3

[472 rows x 4 columns]

In [9]:
import os 
import pandas as pd 
import numpy as np

from dotenv import load_dotenv

import requests 
import json 

from bs4 import BeautifulSoup
import io

import csv

In [ ]:
def print_json_structure(obj, indent=0):
    pad = "  " * indent

    if isinstance(obj, dict):
        for key, value in obj.items():
            print(f"{pad}{key}: {type(value).__name__}")
            print_json_structure(value, indent + 1)

    elif isinstance(obj, list):
        print(f"{pad}[list] len={len(obj)}")
        if obj:
            print_json_structure(obj[0], indent + 1)

In [ ]:
#data chmi

#https://opendata.chmi.cz/meteorology/climate/historical/data/1hour/

In [ ]:
def get_chmi_stations_metadata():
    url = 'https://opendata.chmi.cz/'
    route = '/meteorology/climate/historical/metadata/meta1.json'

    headers = {
        'accept': 'application/json',
        'User-Agent': 'JEM207 DataProcessingCourse (Educational access; contact: 19658413@fsv.cuni.cz)'
    }

    response = requests.get(f'{url}{route}', headers = headers, timeout = 60)
    response.raise_for_status()
    
    response = response.json()
    data_response = response.get('data', {}).get('data', {})

    headers = data_response.get('header', '').split(',')
    values = data_response.get('values', [])

    df = pd.DataFrame(values, columns=headers)
    df.to_csv("data/chmi_stations_metadata.csv", index=False, encoding="utf-8-sig")

get_chmi_stations_metadata()

In [ ]:
### chmi data variables

In [ ]:
def get_chmi_variables_metadata():
    url = 'https://opendata.chmi.cz/'
    route = '/meteorology/climate/historical/metadata/meta2.json'

    headers = {
        'accept': 'application/json',
        'User-Agent': 'JEM207 DataProcessingCourse (Educational access; contact: 19658413@fsv.cuni.cz)'
    }

    response = requests.get(f'{url}{route}', headers = headers, timeout = 60)
    response.raise_for_status()

    response = response.json()
    data_response = response.get('data', {}).get('data', {})

    headers = data_response.get('header', '').split(',')
    values = data_response.get('values', [])

    df = pd.DataFrame(values, columns=headers)
    df.to_csv("data/chmi_variables_metadata.csv", index=False, encoding="utf-8-sig")

get_chmi_variables_metadata()

In [ ]:
### golemio data 


##### air quality stations 

## metadata: https://opendata.chmi.cz//air_quality/recent/metadata/metadata.json

In [ ]:
def set_api_key(token = 'api_key.env'):
    load_dotenv(token)
    api_key = os.getenv('GOLEMIO_API_KEY')
    if api_key:
        print("API key loaded")
    else:
        print("API key not found")
    return api_key

api_key = set_api_key()

✓ API key loaded

In [ ]:
# def get_airquality_stations_metadata():
#     url = 'https://api.golemio.cz/'
#     route = '/v2/airqualitystations'

#     headers = {
#         'X-access-token': api_key, 
#         'accept': 'application/json',
#         'User-Agent': 'JEM207 DataProcessingCourse (Educational access; contact: 19658413@fsv.cuni.cz)'
#     }

#     response = requests.get(f'{url}{route}', headers = headers, timeout = 60)
#     response.raise_for_status()

#     data = response.json()
#     df = pd.json_normalize(data.get('features', {}))

#     tmp = df.explode("properties.measurement.components", ignore_index=True)
#     dirs = pd.json_normalize(
#         tmp["properties.measurement.components"]
#     ).add_prefix("properties.measurement.components.")

#     df = pd.concat([tmp.drop(columns=["properties.measurement.components"]), dirs], axis=1)

#     df.to_csv("data/airquality_stations_metadata.csv", index=False, encoding="utf-8-sig")

# get_airquality_stations_metadata()

In [ ]:
### chmi weather data

# 10 min data download

In [ ]:
def get_chmi_weather_data(start_year = 2025, end_year = 2025):
    base_url = "https://opendata.chmi.cz/"
    route_template = "/meteorology/climate/historical/data/10min/{year}/10m-{wsi}-{ym}.json"

    url_header = {
        'accept': 'application/json',
        'User-Agent': 'JEM207 DataProcessingCourse (Educational access; contact: 19658413@fsv.cuni.cz)'
    }
    
    wsi_dict = pd.read_csv("wsi_dict.csv", encoding="utf-8-sig").set_index("key")["value"].to_dict()

    years = [f"{y}" for y in range(start_year, end_year+1)]
    months = [f"{m:02d}" for m in range(1, 13)]

    results = []

    for wsi in wsi_dict:
        for year in years:
            for month in months:
                ym = f"{year}{month}"
                route = route_template.format(year=year, wsi=wsi, ym=ym)

            try:
                response = requests.get(f"{base_url}{route}", headers=url_header, timeout=60)
                response.raise_for_status()
            except requests.exceptions.RequestException as exc:
                print(f"Request failed for {wsi} {wsi_dict.get(wsi)} {year} {month}: {exc}")
                continue

            response = response.json()
            data_response = response.get('data', {}).get('data', {})

            headers = data_response.get('header', '').split(',')
            values = data_response.get('values', [])

            df_part = pd.DataFrame(values, columns=headers)
            df_part["WSI"] = wsi
            df_part["YEAR"] = year
            df_part["MONTH"] = month

            results.append(df_part)

    df = pd.concat(results, ignore_index=True)
    df.to_csv("data/weather_data_10min.csv", index=False, encoding="utf-8-sig")


get_chmi_weather_data()

Failed for 0-203-0-11201020001 Praha, Vinohrady - Flora 2025 03: 404
Failed for 0-203-0-11105048001 Praha, Zadní Kopanina 2025 01: 404
Failed for 0-203-0-11105048001 Praha, Zadní Kopanina 2025 02: 404
Failed for 0-203-0-11105048001 Praha, Zadní Kopanina 2025 03: 404
Failed for 0-203-0-11105048001 Praha, Zadní Kopanina 2025 04: 404
Failed for 0-203-0-11105048001 Praha, Zadní Kopanina 2025 05: 404
Failed for 0-203-0-11105048001 Praha, Zadní Kopanina 2025 06: 404
Failed for 0-203-0-11105048001 Praha, Zadní Kopanina 2025 07: 404
Failed for 0-203-0-11105048001 Praha, Zadní Kopanina 2025 08: 404
Failed for 0-203-0-11105048001 Praha, Zadní Kopanina 2025 09: 404
Failed for 0-203-0-11105048001 Praha, Zadní Kopanina 2025 10: 404
Failed for 0-203-0-11105048001 Praha, Zadní Kopanina 2025 11: 404
Failed for 0-203-0-11105048001 Praha, Zadní Kopanina 2025 12: 404
Failed for 0-203-0-11202007001 Praha, Suchdol 2025 01: 404
Failed for 0-203-0-11202007001 Praha, Suchdol 2025 02: 404
Failed for 0-203-0-11202007001 Praha, Suchdol 2025 03: 404
Failed for 0-203-0-11202007001 Praha, Suchdol 2025 04: 404
Failed for 0-203-0-11202007001 Praha, Suchdol 2025 05: 404
Failed for 0-203-0-11202007001 Praha, Suchdol 2025 06: 404
Failed for 0-203-0-11202007001 Praha, Suchdol 2025 07: 404
Failed for 0-203-0-11202007001 Praha, Suchdol 2025 08: 404
Failed for 0-203-0-11202007001 Praha, Suchdol 2025 09: 404
Failed for 0-203-0-11202007001 Praha, Suchdol 2025 10: 404
Failed for 0-203-0-11202007001 Praha, Suchdol 2025 11: 404
Failed for 0-203-0-11202007001 Praha, Suchdol 2025 12: 404
Failed for 0-203-0-11201020003 Praha, Chodov 2025 01: 404
Failed for 0-203-0-11201020003 Praha, Chodov 2025 02: 404
Failed for 0-203-0-11201020003 Praha, Chodov 2025 03: 404
Failed for 0-203-0-11201020003 Praha, Chodov 2025 04: 404
Failed for 0-203-0-11201020003 Praha, Chodov 2025 05: 404
Failed for 0-203-0-11201020003 Praha, Chodov 2025 06: 404
Failed for 0-203-0-11201020003 Praha, Chodov 2025 07: 404
Failed for 0-203-0-11201020003 Praha, Chodov 2025 08: 404
Failed for 0-203-0-11201020003 Praha, Chodov 2025 09: 404
Failed for 0-203-0-11201020003 Praha, Chodov 2025 10: 404
Failed for 0-203-0-11201020003 Praha, Chodov 2025 11: 404
Failed for 0-203-0-11201020003 Praha, Chodov 2025 12: 404

In [ ]:
### weather data for 1hour -- if needed

base_url = "https://opendata.chmi.cz/"
route_template = "/meteorology/climate/historical/data/1hour/{year}/1h-{wsi}-{ym}.json"

url_header = {
    'accept': 'application/json',
    'User-Agent': 'JEM207 DataProcessingCourse (Educational access; contact: 19658413@fsv.cuni.cz)'
}

years = [2025]
months = [11] #[f"{m:02d}" for m in range(1, 13)]

results = []

for wsi in wsi_dict:
    for year in years:
        for month in months:
            ym = f"{year}{month}"
            route = route_template.format(year=year, wsi=wsi, ym=ym)

            try:
                response = requests.get(f"{base_url}{route}", headers=url_header, timeout=60)
                response.raise_for_status()
            except requests.exceptions.RequestException as exc:
                print(f"Request failed for {wsi} {wsi_dict.get(wsi)} {year} {month}: {exc}")
                continue

            data_response = response.json()
            data_response = data_response['data']['data']

            headers = data_response['header'].split(',')
            values = data_response['values']

            df_part = pd.DataFrame(values, columns=headers)
            df_part["WSI"] = wsi
            df_part["YEAR"] = year
            df_part["MONTH"] = month

            results.append(df_part)




# df_chmi = pd.concat(results, ignore_index=True)

Failed for 0-203-0-11515 Praha, Klementinum 2025 11: 404
Failed for 0-203-0-11105048001 Praha, Zadní Kopanina 2025 11: 404
Failed for 0-203-0-11101007001 Praha, Brdy 2025 11: 404
Failed for 0-203-0-11202007001 Praha, Suchdol 2025 11: 404
Failed for 0-203-0-11201020003 Praha, Chodov 2025 11: 404

In [ ]:
### golemio 

### air quality data

In [ ]:
# api_url = 'https://api.golemio.cz/'
# route = '/v2/airqualitystations/history'

# headers = {
#     'X-access-token': api_key, 
#     'accept': 'application/json',
#     'User-Agent': 'JEM207 DataProcessingCourse (Educational access; contact: 19658413@fsv.cuni.cz)'
# }

# params = {
#     'from': '2024-05-16T04:27:58.000Z', 
#     'to': '2024-06-18T04:27:58.000Z'
# }

# response = requests.get(f'{api_url}{route}', headers=headers, params=params, timeout=60)

# data = response.json()

In [ ]:
# print(json.dumps(data, indent=2))

{
  "error_message": "Not Found",
  "error_status": 404
}

In [ ]:
# if data:
#     print("Top level keys:", data[0].keys())
#     print("Measurement level keys:", data[0]['measurement'].keys())

Top level keys: dict_keys(['id', 'measurement'])
Measurement level keys: dict_keys(['AQ_hourly_index', 'components'])

In [ ]:
# df = pd.json_normalize(
#     data,
#     record_path=["measurement", "components"],
#     meta=[
#         "id",
#         ["measurement", "AQ_hourly_index"],
#     ],
#     sep=".",
#     errors="raise",
# )

In [ ]:
#### aternative air quality - chmi air quality

def download_latest_data(data_dir_url):
    response = requests.get(data_dir_url, timeout=60)
    response.raise_for_status()
    
    soup = BeautifulSoup(response.text, 'html.parser')
    csv_files = [link.get('href') for link in soup.find_all('a') if link.get('href', '').endswith('.csv')]
    
    if not csv_files:
        raise FileNotFoundError("No CSV files found in the directory.")
    
    # sorting them alphabetically - the last one is the newest
    latest_file = sorted(csv_files)[-1]
    file_url = f"{data_dir_url}{latest_file}"
    
    print(f"Downloading raw data from: {latest_file}")
    data_response = requests.get(file_url)
    data_response.raise_for_status()

    df_data = pd.read_csv(io.StringIO(data_response.text))
    df_data.to_csv("data/airquality_CHMI_stations_data.csv", index=False, encoding="utf-8-sig")

In [ ]:
def download_metadata(metadata_url):
    response = requests.get(metadata_url, timeout=60)
    response.raise_for_status()
    metadata = response.json()

    mapping_list = []

    localities = metadata.get("data", {}).get("Localities", [])

    for locality in localities:
        lon = locality.get("Localization").get("LonAsNumber")
        lat = locality.get("Localization").get("LatAsNumber")
        alt = locality.get("Localization").get("Alt")
        street = locality.get("Address").get("Street")
        city = locality.get("Address").get("City")
        programs = locality.get("MeasuringPrograms")
        for program in programs:
            station_code = program.get("Code")
            measurements = program.get("Measurements")
            for measurement in measurements:
                row = {
                    "id_registration": measurement.get("IdRegistration"),
                    "station_code": station_code,
                    "street": street,
                    "city": city, 
                    "lon": lon, 
                    "lat": lat,
                    "alt": alt,
                    "component_code": measurement.get("ComponentCode"),
                    "component_name": measurement.get("ComponentName"),
                    "unit": measurement.get("UnitAsASCII")
                }
                mapping_list.append(row)

    df_mapping = pd.DataFrame(mapping_list)
    df_mapping.to_csv("data/airquality_CHMI_stations_metadata.csv", index=False, encoding="utf-8-sig")

In [ ]:

META_URL = "https://opendata.chmi.cz/air_quality/recent/metadata/metadata.json"
DATA_URL = "https://opendata.chmi.cz/air_quality/recent/data/"

download_metadata(META_URL)
download_latest_data(DATA_URL)

Downloading raw data from: airquality_1h_avg_CZ_2026042916.csv

In [18]:
#### golemio

### microclimate sensors

In [19]:
# TODO if necessary